[Agent]
# description: date to kill the agent
# type: date
Killdate = 

# description: self deletion in kill date routine
# type: boolean
Self Delete = false

# description: exit method to kill date routine
# type: chooseone
# choices: process, thread
Exit Method = process

# description: used to fork and run routines
# type: string
Spawnto = C:\Windows\System32\notepad.exe

# description: architecture to compile agent
# type: chooseone
# choices: x64, x86
Architecture = x64

# description: technique used to injection shellcode in memory
# type: chooseone
# choices: classic, stomp
Injection Shellcode = classic

# description: technique used to injection PE in memory
# type: chooseone
# choices: reflection
Injection PE = reflection

# description: technique to beacon obfuscate in memory during sleep
# type: chooseone
# choices: timer, none
Mask = none

# description: obfuscate the heap during sleep (note: a mask value other than "none" is required)
# type: boolean
Heap Mask = false

# description: use indirect syscalls
# type: boolean
Indirect Syscall = false

# description: use hardware breakpoint to bypass etw/amsi
# type: boolean
Hardware Breakpoint = false

# description: spoof the call stack of the specifieds winapis
# type: boolean
Call Stack Spoofing = false

# description: executable (.exe), dynamic linked library (.dll), service executable (.svc.exe) and shellcode (.bin)
# type: chooseone
# choices: exe, dll, svc, bin
Format = bin

# description: generate an agent with debug strings. The debug output is handled using DbgPrint and can be viewed in a debugger
# type: boolean
Debug = false